spring.application.name=generic-crud-frameworks

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8r6u9j7uimc73epoht0-a:5432/curd_03ic
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=curd_03ic_user
spring.datasource.password=GTgMBUaGiizrFU3ot0CYe1KbltuUKTLL

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Automatically updates the database schema based on your entities
spring.jpa.hibernate.ddl-auto=update 

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html